[gauntlet]
name = 'Websearch plugin'
description = """
Search the web from gauntlet.
"""

[[entrypoint]]
id = 'web-search'
name = 'web search'
path = 'src/webSearch.tsx'
type = 'inline-view'
description = """
Search the web using Google, DuckDuckGo, or StartPage. Supports direct URL opening, search suggestions, and URL history.
"""

[[preferences]]
id = "preferedSearchEngine"
name = "Prefered search engine"
type = "enum"
default = "google"
description = "Which search engine to use by default"
enum_values = [
    { label = 'Google', value = 'google' },
    { label = 'DuckDuckGo', value = 'duck' },
    { label = 'StartPage', value = 'start' },
    { label = 'Bing', value = 'bing' }
]

[permissions]
main_search_bar = ["read"]
network = ["suggestqueries.google.com:443", "api.duckduckgo.com:443"]

[permissions.filesystem]
write = ["/"]

[permissions.exec]
command = ["xdg-open"]

[[supported_system]]
os = "linux"